import Link from "next/link";
import { ArrowUpRight, CompassMark } from "@/components/icons";
import { CtaBand } from "@/components/cta-band";
import { ModelDiagram } from "@/components/model-diagram";
import { SectionHeading } from "@/components/section-heading";
import { challenges, industries, insights, pillars, processSteps } from "@/lib/site-data";

export default function HomePage() {
  return <><section className="hero"><div className="shell hero__grid"><div className="hero__content"><p className="eyebrow">Technology transformation partner</p><h1>Transform what matters.<br/><em>Build what&apos;s next.</em></h1><p>Northstar helps businesses modernize operations, unlock intelligence from their data, and build digital solutions that create lasting business value.</p><div className="hero__actions"><Link className="button button--gold" href="/contact">Start a conversation <ArrowUpRight/></Link><Link className="text-link" href="/what-we-do">Explore our capabilities <ArrowUpRight/></Link></div></div><div className="hero__orbital" aria-hidden="true"><div className="hero__gridlines"/><div className="hero__circle hero__circle--outer"/><div className="hero__circle hero__circle--middle"/><div className="hero__circle hero__circle--inner"/><CompassMark className="hero__mark"/><span className="hero__point hero__point--one"/><span className="hero__point hero__point--two"/><span className="hero__point hero__point--three"/><p>Direction<br/>meets execution</p></div></div><div className="hero__strap"><span>Business challenge</span><i/><span>Strategy + engineering</span><i/><span>Measurable outcome</span></div></section>
  <section className="section section--paper"><div className="shell model-section"><SectionHeading eyebrow="The Northstar model" title="Three capabilities. One transformation journey." copy="A connected model that moves from the systems you rely on, to the intelligence you need, to what you are ready to build."/><ModelDiagram/></div></section>
  <section className="section"><div className="shell"><SectionHeading eyebrow="Business challenges" title="What are you trying to achieve?" copy="Start with the business problem. We’ll help define the right transformation path."/><div className="challenge-list">{challenges.map(([title, copy, pillar], index) => <Link href={`/what-we-do/${pillar}`} className="challenge" key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{copy}</p></div><ArrowUpRight/></Link>)}</div></div></section>
  <section className="section section--ink"><div className="shell"><SectionHeading inverse eyebrow="Capabilities" title="Modernize. Intelligence. Build." copy="Business capabilities that bring strategy, technology and execution together."/><div className="capability-grid">{pillars.map((pillar) => <Link className="capability" href={`/what-we-do/${pillar.slug}`} key={pillar.slug}><span>{pillar.number}</span><h3>{pillar.name}</h3><p>{pillar.title}</p><ul>{pillar.services.map((service) => <li key={service.slug}>{service.title}</li>)}</ul><b>Explore {pillar.name} <ArrowUpRight/></b></Link>)}</div></div></section>
  <section className="section"><div className="shell process-layout"><SectionHeading eyebrow="How we work" title="From business challenge to measurable outcome." copy="Strategy without execution doesn’t transform a business. Northstar brings strategy and engineering together to move from ideas to working capabilities."/><ol className="process-list">{processSteps.map(([number, title, copy]) => <li key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol></div></section>
  <section className="section section--paper"><div className="shell two-column-statement"><div><p className="eyebrow">Transformation in practice</p><h2>Complex work needs a clear story.</h2></div><div><p>Case studies will share the challenge, approach, capability and outcome behind approved work. No client details or metrics are published until they are ready to be shared.</p><Link className="text-link" href="/case-studies">View case studies <ArrowUpRight/></Link></div></div></section>
  <section className="section"><div className="shell"><SectionHeading eyebrow="Why Northstar" title="Technology with business purpose."/><div className="principles"><article><span>01</span><h3>Business-first technology</h3><p>We start with the business problem, not the technology.</p></article><article><span>02</span><h3>Strategy + engineering</h3><p>We turn strategy into working systems and capabilities.</p></article><article><span>03</span><h3>Modernization without disruption</h3><p>We help evolve critical operations while keeping the business moving.</p></article><article><span>04</span><h3>Practical AI</h3><p>We focus on AI and automation where it can create meaningful business value.</p></article><article><span>05</span><h3>Outcome-oriented delivery</h3><p>We focus on the difference the work makes, not simply completing an implementation.</p></article></div></div></section>
  <section className="section section--slate"><div className="shell"><SectionHeading inverse eyebrow="Industries" title="Technology built around your business." copy="Different industries have different customers, processes, regulations and operational realities."/><div className="industry-grid">{industries.map(([name, copy], index) => <article key={name}><span>0{index + 1}</span><h3>{name}</h3><p>{copy}</p></article>)}</div><Link className="text-link text-link--light" href="/industries">Explore industries <ArrowUpRight/></Link></div></section>
  <section className="section"><div className="shell insights-preview"><SectionHeading eyebrow="Northstar insights" title="Perspectives with practical value." copy="Future articles will explore modernization, data, AI and digital engineering - without turning insight into noise."/><div className="insight-tags">{insights.map((insight, index) => <span key={insight}><b>0{index + 1}</b>{insight}</span>)}</div><Link className="text-link" href="/insights">Explore insights <ArrowUpRight/></Link></div></section>
  <CtaBand/></>;
}
